version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Build wheel package
          command: |
            sed -i -r '/^(coverage|pylint|mypy|sphinx|autodocsumm)/Id' requirements.txt
            pip install --user -r requirements.txt
            ./setup.py bdist_wheel
      - persist_to_workspace:
          root: .
          paths: ./dist/*.whl
  test-py35: &test-py35
    docker:
      - image: circleci/python:3.5
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unit tests
          command: |
            pip install --user ./dist/*.whl
            python -m yamlargparse_tests
  test-py36:
    <<: *test-py35
    docker:
      - image: circleci/python:3.6
  test-py37:
    <<: *test-py35
    docker:
      - image: circleci/python:3.7
  publish-pypi:
    docker:
      - image: mauvilsa/docker-twine:1.11.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish Release on PyPI
          command: twine upload --username "${PYPI_USER}" --password "${PYPI_PASS}" ./dist/*.whl

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build: &buildreq
          filters: &tagfilter
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - test-py35: &testreq
          <<: *buildreq
          requires:
            - build
      - test-py36:
          <<: *testreq
      - test-py37:
          <<: *testreq
      - publish-pypi:
          filters:
            branches:
              ignore: /.*/
            <<: *tagfilter
          context: yamlargparse-context
          requires:
            - test-py35
            - test-py36
            - test-py37
